# Generated by Django 4.2.2 on 2023-06-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture", models.ImageField(upload_to="media/data_pictures/")),
                ("node_origination", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField()),
                ("file_type", models.CharField(max_length=50)),
            ],
        ),
    ]
