# Generated by Django 4.2.2 on 2023-07-13 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_number', models.IntegerField(null=True, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('num_sensors', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('date_created', models.DateField(null=True)),
                ('date_inputted', models.DateField(null=True)),
                ('time_created', models.TimeField(null=True)),
                ('time_inputted', models.TimeField(null=True)),
                ('date_difference', models.DateField(null=True)),
                ('time_difference', models.TimeField(null=True)),
                ('file_type', models.CharField(max_length=50, null=True)),
                ('dataid', models.IntegerField(null=True)),
                ('node_origination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.node', to_field='node_number')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=255)),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.node', to_field='node_number')),
            ],
        ),
        migrations.CreateModel(
            name='PictureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('date_created', models.DateTimeField(null=True)),
                ('file_type', models.CharField(max_length=50, null=True)),
                ('dataid', models.IntegerField(null=True)),
                ('node_origination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.node', to_field='node_number')),
            ],
        ),
        migrations.CreateModel(
            name='HumidityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('date_created', models.DateTimeField(null=True)),
                ('file_type', models.CharField(max_length=50, null=True)),
                ('dataid', models.IntegerField(null=True)),
                ('node_origination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.node')),
            ],
        ),
    ]
