# Generated by Django 4.2.2 on 2023-07-13 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperaturedata',
            name='time_created',
        ),
        migrations.RemoveField(
            model_name='temperaturedata',
            name='time_difference',
        ),
        migrations.RemoveField(
            model_name='temperaturedata',
            name='time_inputted',
        ),
    ]
