# Generated by Django 4.2.2 on 2023-06-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='picture',
        ),
        migrations.AddField(
            model_name='data',
            name='dataid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='file_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='node_origination',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
