# Generated by Django 4.2.2 on 2023-07-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_temperaturedata_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturedata',
            name='date_difference',
            field=models.IntegerField(null=True),
        ),
    ]
