# Generated by Django 4.2.2 on 2023-07-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_temperaturedata_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturedata',
            name='date_difference',
            field=models.DateTimeField(null=True),
        ),
    ]
