# Generated by Django 4.2.2 on 2023-07-13 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_temperaturedata_time_difference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperaturedata',
            name='date_difference',
        ),
    ]
