# Generated by Django 4.2.2 on 2023-07-13 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_remove_temperaturedata_date_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='humiditydata',
            name='date_inputted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='humiditydata',
            name='time_difference',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='picturedata',
            name='date_inputted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='picturedata',
            name='time_difference',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='humiditydata',
            name='node_origination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.node', to_field='node_number'),
        ),
    ]
