# Generated by Django 3.2.7 on 2023-07-24 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_auto_20230720_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humiditydata',
            name='date_created_seconds',
        ),
        migrations.RemoveField(
            model_name='picturedata',
            name='date_created_seconds',
        ),
        migrations.RemoveField(
            model_name='temperaturedata',
            name='date_created_seconds',
        ),
    ]
